all:
  hosts:
  # host agnostic vars
  vars:
    github_username: mastermindzh
    timezone: "Europe/Amsterdam"

  # actual hosts
  children:
    # all servers running Ubuntu
    ubuntu:
      # "Ubuntu" variables
      vars:
      hosts:
        # a named host (pihole)
        pihole:
          # host specific variables
          ansible_host: 10.10.1.2 # host IP, because it is named
        # unnamed hosts
        # 10.10.1.0:
