all:
  hosts:
  # host agnostic vars
  vars:
    github_username: mastermindzh
    timezone: "Europe/Amsterdam"
    # ansible_user: your_username # use this to override the user to connect to machines as.

  # actual hosts
  children:
    # all servers running Ubuntu
    ubuntu:
      # "Ubuntu" variables
      vars:
      hosts:
        # a named host (pihole)
        pihole:
          # host specific variables
          ansible_host: 10.10.1.2 # host IP, because it is named

        # raspberry pis
        10.10.1.3:
          label: "kube-pi-1"
        10.10.1.4:
          label: "kube-pi-2"
