- name: Set timezone and configure timesyncd
  hosts: "*"
  become: true
  tasks:
    - name: Set the timezone
      command: timedatectl set-timezone {{ timezone }}

    - name: Stop timesyncd
      systemd:
        name: systemd-timesyncd.service
        state: stopped

    - name: Copy over the timesyncd config
      template:
        src: ../../../templates/timesyncd.conf
        dest: /etc/systemd/timesyncd.conf
        mode: 0644

    - name: Start timesyncd
      systemd:
        name: systemd-timesyncd.service
        state: started
